Pin attrs to avoid pytest fails on deprecated API
With this commit we pin pytest's dependency `attrs` to avoid the
following error when running tests:

TypeError: attrib() got an unexpected keyword argument 'convert'

This has already been fixed in pytest 5.2.0 and we will upgrade
separately to that version but this requires more changes and will
require more testing.