Improve compatibility when loading invalid JSON
Previously we caught `JSONDecodeError` in the error handler when loading
JSON. However, this class has been introduced in Python 3.5 and thus we
fail on Python 3.4 with a confusing error message:

```
AttributeError: 'module' object has no attribute 'JSONDecodeError'
```

To avoid this situation, we broaden the `except` clause and also
introduce a new test case to ensure error handling works correctly on
all supported Python versions.

Closes #564
Relates #565